### ISSUE TITLE
Create STYLEGUIDE.md

### ISSUE THREAD

**Issue by Duskt** [jacob-horton/flipster#37]
It might be useful to create a style guide for consistency in clarity as well as to serve as a useful reference.
Some possible points of discussion:
- [ ] Type naming conventions in requests/response (as mentioned by @jacob-horton )
Currently types are defined in Rust and exported using ts-rs into web/src/types. We currently use XGet or XInsert to describe types passed to requests (GET or POST, respectively) but this convention is up for debate.

- [ ] CSS practices

A proposed system for something akin to encapsulation:
- When passing a className to a defined component, it should apply only to the outermost element and not contradict any other styles. 
- I also think a set width, height, and display: block should be present on an element containing children passed in through props - this means children can be layed out by replacing the children passed with a ``<div className="w-full h-full">`` without resulting in unexpected behaviour, say from using a flexbox or lack of.
```jsx
return <div className={className ?? ""}> // no other styles here
    {someReactNode}
    <div className="w-full h-full">{children}</div> // block by default
</div>
```

- [ ] Component conventions?
I have personally just been naming components based on what feels right and what the surrounding files have used. 
We write components as ``const Component = ({ propOne, propTwo }) => { ... }`` but this can easily be seen by looking at code in the repository.

- [ ] Tailwind style class ordering?
As for me, I currently use something like ``flex size flex-parent-properties flex-child-properties styling`` (flex-parent-properties e.g. justify-content, align-items) (flex-child-properties e.g. align-self, grow, shrink). Formalising this could be pedantic, though.

- [x] Prettier + ESLint

**Comment by jacob-horton** [comment]
Overall, I agree with this, I think its really good

---

The first line in the block of code I think should be simplified to
```jsx
return <div className={className}> // no other styles here
```
as undefined is an accepted value here

ALso, we should only wrap the component in a div with className when required to avoid unnecessary clutter

---

An idea for naming convention of API types could be  XGetReq, XPostReq, XGetResp, XPostResp

---

For better readability and typability use `function name(...) {}` for named functions, including components. Arrow functions e.g. `() => {}` should only be used for throwaway functions i.e. ones that aren't named and are only used once

---

Not sure on component names, I think just intuition is probably fine. Maybe we need to come up with folder structure, especially regarding components used in specific pages

---

We should try to use [HTML elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element) in their proper place e.g. `<ul>` and `<li>` for lists, `<dialog>` for modals, etc.

---

We should try to use [CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete) equivalents for [HTTP](https://en.wikipedia.org/wiki/HTTP#Request_methods) endpoints:
| CRUD | HTTP |
| ------ | ------ |
| Create | POST (create) or PUT (create/replace) |
|  Read | GET |
| Update | PUT (replace) or PATCH (modify) |
| Delete | DELETE |

**Comment by Duskt** [comment]
Solved via the style guide page in the newly created documentation wiki.
